In [1]:
import numpy as np  

In [7]:
a = [1,2,3,44]
type(a)
print(a)

[1, 2, 3, 44]


In [5]:
a.ndim

AttributeError: 'list' object has no attribute 'ndim'

In [11]:
a = np.array([1,2,3,44])
print(a)
print(type(a))
print(a.ndim)  # ndim is the keyword which is used to find the number of dimension 

[ 1  2  3 44]
<class 'numpy.ndarray'>
1


In [12]:
a = np.array([[1,2,3,44]])
print(a)
print(type(a))
print("Number of dimensions = " , a.ndim)

[[ 1  2  3 44]]
<class 'numpy.ndarray'>
Number of dimensions =  2


In [13]:
a = np.array([[[1,2,3,44]]])
print(a)
print(type(a))
print("Number of dimensions = " , a.ndim)

[[[ 1  2  3 44]]]
<class 'numpy.ndarray'>
Number of dimensions =  3


## matrix 

In [15]:
a = np.array([[10,11,12] , [10,21,33]])
print(a)
print(a.ndim)

[[10 11 12]
 [10 21 33]]
2


In [17]:
a = np.array([[10,11,12] , [10,21,33]])
print(a)
print(a.ndim)

[[10 11 12]
 [10 21 33]]
2


In [19]:
import warnings 
warnings.filterwarnings('ignore')

In [20]:
a = np.array([[10,11,12] , [10,21,33,55]])
print(a)
print(a.ndim)

[list([10, 11, 12]) list([10, 21, 33, 55])]
1


In [23]:
a = np.array([[[10,11,12] , [10,21,33] , [21,22,23]]])
print(a)
print(a.ndim)

[[[10 11 12]
  [10 21 33]
  [21 22 23]]]
3


In [25]:
for i in range(1,11):
    print(i,end=" ")

1 2 3 4 5 6 7 8 9 10 

In [28]:
### arange same like range n-1

a = np.arange(1,11)
print(a)
print(a.ndim)

[ 1  2  3  4  5  6  7  8  9 10]
1


In [29]:
a = np.arange(1,11,2)
print(a)
print(a.ndim)

[1 3 5 7 9]
1


In [36]:
b = np.arange(1,11 , dtype = float)
print(b)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [38]:
a = np.array([[[10,11,12] , [10,21,33] , [21,22,23]]] , dtype = float)
print(a)
print(a.ndim)

[[[10. 11. 12.]
  [10. 21. 33.]
  [21. 22. 23.]]]
3


In [39]:
### Linespace means halfs 

# 10 to 20 -> 10 12.5 15 17.5 20

a = np.linspace(10,20,6)
a

array([10., 12., 14., 16., 18., 20.])

In [41]:
a = np.linspace(10,20,5 , dtype = int)
a

array([10, 12, 15, 17, 20])

### zeros 

In [43]:
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [45]:
a = np.zeros((5,5),dtype = int)
a

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

### ones 

In [46]:
a = np.ones((5,5),dtype = int)
a

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### random concepts 

In [50]:
np.random.randint(10,20)  # random value will be collected 

10

In [52]:
np.random.rand(3,4)  # mostly values will be lie in between 0 to 1 only 

array([[0.27171819, 0.48752252, 0.05813985, 0.57687933],
       [0.06584346, 0.88523434, 0.94338006, 0.05500982],
       [0.88361322, 0.5992301 , 0.01680215, 0.16109396]])

In [53]:
np.random.randn(3,4)   # u will get the vlaues from standard deviation point 

array([[ 1.77635864, -0.09368659, -0.58894971, -0.70215188],
       [ 0.70912265,  2.39036002, -0.76761884,  1.45990361],
       [ 0.85247746, -0.97924846, -0.29075173, -1.0980916 ]])

In [55]:
np.random.random((5,4))  # randomlly we will collect the values 

array([[0.13059621, 0.21338915, 0.89505845, 0.98094413],
       [0.87240147, 0.70512   , 0.01712552, 0.68571784],
       [0.58296239, 0.44252534, 0.74348152, 0.15912424],
       [0.38036401, 0.32001076, 0.26930313, 0.89979048],
       [0.19555542, 0.37249451, 0.1998021 , 0.03201161]])

### small slicing operations 

In [56]:
a = np.array([[[10,11,12] , [10,21,33] , [21,22,23]]] , dtype = int)
print(a)
print(a.ndim)

[[[10 11 12]
  [10 21 33]
  [21 22 23]]]
3


In [59]:
a = np.array([[10,11,12] , [10,21,33] , [21,22,23]] , dtype = int)
print(a)
print(a.ndim)

[[10 11 12]
 [10 21 33]
 [21 22 23]]
2


In [62]:
a[1][2]

33

#### creating a dimensions on our own 

In [64]:
# reshaping 

a = np.arange(1,61)
print(a)
print(a.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60]
1


In [66]:
# 1d to 2d
b = np.arange(1,61).reshape(10,6)
print(b)
print(b.ndim)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]
 [49 50 51 52 53 54]
 [55 56 57 58 59 60]]
2


In [67]:
# 1d or 2d to 3d 

c = np.arange(1,61).reshape(5,2,6)
print(c)
print(c.ndim)

[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]]

 [[13 14 15 16 17 18]
  [19 20 21 22 23 24]]

 [[25 26 27 28 29 30]
  [31 32 33 34 35 36]]

 [[37 38 39 40 41 42]
  [43 44 45 46 47 48]]

 [[49 50 51 52 53 54]
  [55 56 57 58 59 60]]]
3


### 1-d array 

In [4]:
a = np.arange(1,61)
print(a)
print("The number of dimesions = ",a.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60]
The number of dimesions =  1


In [5]:
## accessing the value 
a[8]

9

In [6]:
a[39]

40

In [35]:
a = np.array([10,11,12,13])
print(a)
print(a.ndim)

[10 11 12 13]
1


In [36]:
a[1]

11

In [37]:
a.shape

(4,)

In [33]:
b = a.reshape(-1,1)
print(b)

[[10]
 [11]
 [12]
 [13]]


In [34]:
b.shape

(4, 1)

In [38]:
b = a.reshape(1,-1)
print(b)

[[10 11 12 13]]


In [39]:
b.shape

(1, 4)

### 2-d array 

In [7]:
a = np.arange(1,61).reshape(10,6)
print(a)
print()
print('the number of dimesions = ' , a.ndim)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]
 [49 50 51 52 53 54]
 [55 56 57 58 59 60]]

the number of dimesions =  2


In [8]:
a[2][3]

16

In [9]:
a[7][4]

47

In [13]:
a = np.array([[10,11,12,13]])
print(a)

[[10 11 12 13]]


In [15]:
a[0][1]

11

In [44]:
a = np.array([[10,11,12,13] , 
             [21,22,23,24],
             [41,42,43,44]])
print(a)
print(a.ndim)

[[10 11 12 13]
 [21 22 23 24]
 [41 42 43 44]]
2


In [41]:
a[1][2]

23

In [45]:
a.shape   # shape funcion will gives us how many rows and columns are there 

(3, 4)

In [43]:
a.size   # size will tell us how many values are there 

12

### round 

In [46]:
a = 12.2
b = np.round(a)
print(b)

12.0


In [47]:
a = 12.6
b = np.round(a)
print(b)

13.0


In [48]:
a = 12.5
b = np.round(a)
print(b)

12.0


In [50]:
a = 12.55
b = np.round(a)
print(b)

13.0


### 3-d arrays 

In [51]:
a = np.arange(1,61).reshape(5,2,6)
print(a)

[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]]

 [[13 14 15 16 17 18]
  [19 20 21 22 23 24]]

 [[25 26 27 28 29 30]
  [31 32 33 34 35 36]]

 [[37 38 39 40 41 42]
  [43 44 45 46 47 48]]

 [[49 50 51 52 53 54]
  [55 56 57 58 59 60]]]


In [52]:
print(a.ndim)

3


In [53]:
print(a.shape)

(5, 2, 6)


In [54]:
print(a.size)

60


In [56]:
a[3][0][4]

41

In [57]:
a[1][1][2]

21

In [58]:
a = np.arange(1,61).reshape(5,4,3)
print(a)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]

 [[37 38 39]
  [40 41 42]
  [43 44 45]
  [46 47 48]]

 [[49 50 51]
  [52 53 54]
  [55 56 57]
  [58 59 60]]]


In [59]:
a[1][1][1]

17

### operations using axis = 1 and axis = 0

In [60]:
a = np.arange(1,61).reshape(10,6)
print(a)
print()
print('the number of dimesions = ' , a.ndim)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]
 [49 50 51 52 53 54]
 [55 56 57 58 59 60]]

the number of dimesions =  2


In [61]:
# axis = 1 means row vise 
# axis = 0 means column vise 

In [62]:
sol = np.sum(a)
sol  # total sum

1830

In [64]:
a.shape

(10, 6)

In [63]:
rows = np.sum(a , axis = 1)
rows

array([ 21,  57,  93, 129, 165, 201, 237, 273, 309, 345])

In [66]:
rows[3]

129

In [65]:
    col = np.sum(a , axis = 0)
    col

array([280, 290, 300, 310, 320, 330])

### math operations 

In [67]:
a = [2,3,4,5]
b = np.sqrt(a)
b

array([1.41421356, 1.73205081, 2.        , 2.23606798])

In [68]:
a = [2,3,4,5]
b = np.sin(a)
b

array([ 0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [69]:
a = [2,3,4,5]
b = np.cos(a)
b

array([-0.41614684, -0.9899925 , -0.65364362,  0.28366219])

### Vstact and hstack

In [70]:
a = np.arange(1,61).reshape(10,6)
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]
 [49 50 51 52 53 54]
 [55 56 57 58 59 60]]


In [71]:
b = np.arange(61,121).reshape(10,6)
print(b)

[[ 61  62  63  64  65  66]
 [ 67  68  69  70  71  72]
 [ 73  74  75  76  77  78]
 [ 79  80  81  82  83  84]
 [ 85  86  87  88  89  90]
 [ 91  92  93  94  95  96]
 [ 97  98  99 100 101 102]
 [103 104 105 106 107 108]
 [109 110 111 112 113 114]
 [115 116 117 118 119 120]]


In [72]:
### vertical stacking means placing one array one the top of another array 

In [74]:
vstack = np.vstack((a,b))
vstack


array([[  1,   2,   3,   4,   5,   6],
       [  7,   8,   9,  10,  11,  12],
       [ 13,  14,  15,  16,  17,  18],
       [ 19,  20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36],
       [ 37,  38,  39,  40,  41,  42],
       [ 43,  44,  45,  46,  47,  48],
       [ 49,  50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66],
       [ 67,  68,  69,  70,  71,  72],
       [ 73,  74,  75,  76,  77,  78],
       [ 79,  80,  81,  82,  83,  84],
       [ 85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96],
       [ 97,  98,  99, 100, 101, 102],
       [103, 104, 105, 106, 107, 108],
       [109, 110, 111, 112, 113, 114],
       [115, 116, 117, 118, 119, 120]])

In [75]:
vstack.shape

(20, 6)

In [76]:
vstack.size

120

In [77]:
### Horizantal stacking means we are going to place the values side by side 

In [78]:
hstack = np.hstack((a,b))
hstack

array([[  1,   2,   3,   4,   5,   6,  61,  62,  63,  64,  65,  66],
       [  7,   8,   9,  10,  11,  12,  67,  68,  69,  70,  71,  72],
       [ 13,  14,  15,  16,  17,  18,  73,  74,  75,  76,  77,  78],
       [ 19,  20,  21,  22,  23,  24,  79,  80,  81,  82,  83,  84],
       [ 25,  26,  27,  28,  29,  30,  85,  86,  87,  88,  89,  90],
       [ 31,  32,  33,  34,  35,  36,  91,  92,  93,  94,  95,  96],
       [ 37,  38,  39,  40,  41,  42,  97,  98,  99, 100, 101, 102],
       [ 43,  44,  45,  46,  47,  48, 103, 104, 105, 106, 107, 108],
       [ 49,  50,  51,  52,  53,  54, 109, 110, 111, 112, 113, 114],
       [ 55,  56,  57,  58,  59,  60, 115, 116, 117, 118, 119, 120]])

### simple operations 

In [79]:
a = [1,2,3,4]
print(np.sum(a))

10


In [80]:
max(a)

4

In [81]:
min(a)

1

### diagonal function 


In [84]:
diag = np.diag([10,11,15,21])
diag

array([[10,  0,  0,  0],
       [ 0, 11,  0,  0],
       [ 0,  0, 15,  0],
       [ 0,  0,  0, 21]])

### ravel 

In [85]:
a = np.array([
    [10,11,12,13],
    [100,200,300,400]])
print(a)

[[ 10  11  12  13]
 [100 200 300 400]]


In [86]:
## ravel function is goint to change 2d array to 1 d array 


In [87]:
sol = a.ravel()
sol

array([ 10,  11,  12,  13, 100, 200, 300, 400])

In [103]:
a = np.array([[
    [10,11,12,13],
    [100,200,300,400]]])
print(a)
print(a.ndim)

[[[ 10  11  12  13]
  [100 200 300 400]]]
3


In [104]:
sol = a.ravel()
sol

array([ 10,  11,  12,  13, 100, 200, 300, 400])

## Transpose 

In [90]:
a = np.array([
    [10,11,12,13],
    [100,200,300,400]])
print(a)
print(a.ndim)

[[ 10  11  12  13]
 [100 200 300 400]]
2


In [92]:
### Transpose means converting rows to columns and columns to rows

In [91]:
a.T

array([[ 10, 100],
       [ 11, 200],
       [ 12, 300],
       [ 13, 400]])

In [93]:
## absolute means converting negative values into positive 
a = np.abs(-100)
a

100

In [94]:
v = np.abs(-79)
v

79

### concatination 

In [95]:
# concatination means adding the matrix 



In [96]:
a = np.array([
    [10,11,12,13],
    [100,200,300,400]])


In [97]:
b = np.array([
    [1,2,3,4],
    [113,114,115,116]])

In [98]:
adding = np.concatenate((a,b))
adding

array([[ 10,  11,  12,  13],
       [100, 200, 300, 400],
       [  1,   2,   3,   4],
       [113, 114, 115, 116]])

## eye 

In [99]:
# eye means indentity matrix 

In [102]:
a = np.eye(3,3 , dtype = int)
a

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [105]:
a = np.array([[100,12,13],
             [1,100,3]])
a

array([[100,  12,  13],
       [  1, 100,   3]])

### adding 2 arrays 

In [106]:
a = np.array([[1,2,3,4],
             [10,11,12,13]])
a

array([[ 1,  2,  3,  4],
       [10, 11, 12, 13]])

In [108]:
b = np.array([[100,200, 300,400],
             [31,33,34,35]])
b

array([[100, 200, 300, 400],
       [ 31,  33,  34,  35]])

In [109]:
a + b

array([[101, 202, 303, 404],
       [ 41,  44,  46,  48]])